export const NAV_ITEMS = [
  { href: '/', label: 'Dashboard', module: 'analytics', icon: '▣' },
  { href: '/leads', label: 'Leads & Inquiries', module: 'leads', icon: '✉' },
  { href: '/announcements', label: 'Announcements', module: 'announcements', icon: '⚑' },
  { href: '/services', label: 'Services', module: 'services', icon: '✚' },
  { href: '/providers', label: 'Providers', module: 'providers', icon: '♟' },
  { href: '/insurance', label: 'Insurance & Fees', module: 'insurance', icon: '$' },
  { href: '/testimonials', label: 'Reviews', module: 'testimonials', icon: '★' },
  { href: '/faqs', label: 'FAQs', module: 'faqs', icon: '?' },
  { href: '/locations', label: 'Locations & Hours', module: 'locations', icon: '⌂' },
  { href: '/blog', label: 'Blog & Resources', module: 'blog', icon: '✎' },
  { href: '/media', label: 'Photos & Media', module: 'media', icon: '🖼' },
  { href: '/videos', label: 'Videos', module: 'videos', icon: '▶' },
  { href: '/sections', label: 'Page Sections', module: 'sections', icon: '▤' },
  { href: '/booking', label: 'Booking Links', module: 'booking', icon: '📅' },
  { href: '/seo', label: 'SEO & Sharing', module: 'seo', icon: '🔍' },
  { href: '/analytics', label: 'Analytics', module: 'analytics', icon: '📈' },
  { href: '/users', label: 'Staff & Access', module: 'users', icon: '👤' },
] as const;
